# Generated by Django 5.2.12 on 2026-03-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourinterviewer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewsession',
            name='completed',
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='experience_level',
            field=models.CharField(default='fresher', max_length=50),
        ),
    ]
