# Generated by Django 5.2.12 on 2026-03-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourinterviewer', '0002_remove_interviewsession_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
