# Generated by Django 5.2.12 on 2026-03-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourinterviewer', '0003_interviewsession_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='language',
            field=models.CharField(blank=True, help_text='e.g., Java, Python, React', max_length=50, null=True),
        ),
    ]
