# Generated by Django 5.2.12 on 2026-04-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourinterviewer', '0004_interviewsession_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='emotion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
